# -*- coding: utf-8 -*-
"""SYMPTOMS lexicon data, split out for manageable file size."""

SYMPTOMS = {
    "fever": {
        "bn": ["জ্বর", "গায়ে জ্বর", "জ্বর জ্বর ভাব"],
        "bl": ["jor", "jwor", "gaye jor"],
        "en": ["fever", "feverish"],
        "specialty": "General Medicine", "level": 2,
    },
    "high_fever": {
        "bn": ["তীব্র জ্বর", "অনেক জ্বর", "খুব জ্বর", "১০৩ ডিগ্রি জ্বর"],
        "bl": ["onek jor", "khub jor", "103 jor"],
        "en": ["high fever", "very high temperature", "103 fever"],
        "specialty": "General Medicine", "level": 3,
    },
    "cough": {
        "bn": ["কাশি", "শুকনো কাশি", "কফ"],
        "bl": ["kashi", "shukna kashi", "cough"],
        "en": ["cough", "dry cough", "coughing"],
        "specialty": "Pulmonology", "level": 2,
    },
    "runny_nose": {
        "bn": ["সর্দি", "নাক দিয়ে পানি পড়ছে", "নাক বন্ধ"],
        "bl": ["shordi", "nak bondho"],
        "en": ["runny nose", "blocked nose", "cold"],
        "specialty": "General Medicine", "level": 1,
    },
    "sore_throat": {
        "bn": ["গলা ব্যথা", "গলায় ব্যথা", "ঢোক গিলতে কষ্ট"],
        "bl": ["gola betha", "gola byatha"],
        "en": ["sore throat", "throat pain", "pain swallowing"],
        "specialty": "ENT", "level": 2,
    },
    "chest_pain": {
        "bn": ["বুকে ব্যথা", "বুকে চাপ", "বুকে চাপ চাপ লাগছে", "বুক ব্যথা"],
        "bl": ["buke betha", "bukey pain", "buke chap"],
        "en": ["chest pain", "chest pressure", "pain in chest"],
        "specialty": "Cardiology", "level": 4,
    },
    "shortness_of_breath": {
        "bn": ["শ্বাসকষ্ট", "শ্বাস নিতে কষ্ট", "দম বন্ধ লাগছে", "নিঃশ্বাস নিতে সমস্যা"],
        "bl": ["shash kosto", "shash nite koshto", "dom bondho"],
        "en": ["shortness of breath", "breathing difficulty", "difficulty breathing",
               "difficulty in breathing", "trouble breathing", "breathless",
               "cant breathe properly", "cannot breathe properly",
               "hard to breathe", "struggling to breathe"],
        "specialty": "Pulmonology", "level": 4,
    },
    "palpitations": {
        "bn": ["বুক ধড়ফড়", "বুক ধড়ফড় করছে", "হার্ট দ্রুত চলছে"],
        "bl": ["buk dhorfor", "heart beat besi"],
        "en": ["palpitations", "heart racing", "irregular heartbeat"],
        "specialty": "Cardiology", "level": 3,
    },
    "heartburn": {
        "bn": ["বুক জ্বালাপোড়া", "গ্যাস্ট্রিকের সমস্যা", "টক ঢেকুর", "অ্যাসিডিটি"],
        "bl": ["buk jalapora", "gastric problem", "acidity"],
        "en": ["heartburn", "acidity", "acid reflux", "gastric pain"],
        "specialty": "Gastroenterology", "level": 1,
    },
    "headache": {
        "bn": ["মাথাব্যথা", "মাথা ব্যথা", "মাথা ধরেছে"],
        "bl": ["matha betha", "matha byatha", "mathabetha"],
        "en": ["headache", "head pain"],
        "specialty": "Neurology", "level": 2,
    },
    "sudden_severe_headache": {
        "bn": ["হঠাৎ তীব্র মাথাব্যথা", "জীবনের সবচেয়ে খারাপ মাথাব্যথা"],
        "bl": ["hothat tibro matha betha"],
        "en": ["sudden severe headache", "worst headache of my life", "thunderclap headache"],
        "specialty": "Neurology", "level": 4,
    },
    "dizziness": {
        "bn": ["মাথা ঘোরা", "মাথা ঘু় ছে", "চোখে অন্ধকার দেখা"],
        "bl": ["matha ghora", "matha ghurche"],
        "en": ["dizziness", "feeling dizzy", "lightheaded"],
        "specialty": "General Medicine", "level": 2,
    },
    "vomiting": {
        "bn": ["বমি", "বমি হচ্ছে", "বমি বমি ভাব"],
        "bl": ["bomi", "bomi hocche", "vomit"],
        "en": ["vomiting", "nausea", "throwing up"],
        "specialty": "Gastroenterology", "level": 2,
    },
    "blood_vomiting": {
        "bn": ["রক্ত বমি", "রক্ত বমি হচ্ছে", "বমির সাথে রক্ত", "বমিতে রক্ত"],
        "bl": ["rokto bomi", "rokto bomi hocche", "bomir sathe rokto"],
        "en": ["vomiting blood", "blood in vomit"],
        "specialty": "Gastroenterology", "level": 5,
    },
    "diarrhea": {
        "bn": ["পাতলা পায়খানা", "ডায়রিয়া", "বারবার পায়খানা"],
        "bl": ["patla paykhana", "diarrhea", "loose motion"],
        "en": ["diarrhea", "loose motion", "loose stools"],
        "specialty": "Gastroenterology", "level": 2,
    },
    "bloody_stool": {
        "bn": ["পায়খানার সাথে রক্ত", "মলের সাথে রক্ত", "কালো পায়খানা"],
        "bl": ["paykhanar sathe rokto", "kalo paykhana"],
        "en": ["blood in stool", "black stool", "bloody stool"],
        "specialty": "Gastroenterology", "level": 4,
    },
    "abdominal_pain": {
        "bn": ["পেট ব্যথা", "পেটে ব্যথা", "পেট কামড়াচ্ছে"],
        "bl": ["pet betha", "pete betha", "pet byatha"],
        "en": ["stomach pain", "abdominal pain", "belly pain"],
        "specialty": "Gastroenterology", "level": 2,
    },
    "burning_urination": {
        "bn": ["প্রস্রাবে জ্বালাপোড়া", "প্রস্রাবের সময় ব্যথা"],
        "bl": ["prosrabe jalapora", "prosrab e betha"],
        "en": ["burning urination", "pain while urinating", "burning sensation urine"],
        "specialty": "Urology", "level": 2,
    },
    "blood_in_urine": {
        "bn": ["প্রস্রাবে রক্ত", "লাল প্রস্রাব"],
        "bl": ["prosrab e rokto"],
        "en": ["blood in urine", "red urine"],
        "specialty": "Urology", "level": 3,
    },
    "joint_pain": {
        "bn": ["হাঁটুতে ব্যথা", "গিরায় গিরায় ব্যথা", "জয়েন্টে ব্যথা", "হাঁটু ব্যথা"],
        "bl": ["hatu betha", "joint e betha", "giray betha"],
        "en": ["knee pain", "joint pain", "joint ache"],
        "specialty": "Orthopedics", "level": 2,
    },
    "back_pain": {
        "bn": ["কোমর ব্যথা", "কোমরে ব্যথা", "পিঠে ব্যথা"],
        "bl": ["komor betha", "pith betha", "back pain"],
        "en": ["back pain", "lower back pain", "waist pain"],
        "specialty": "Orthopedics", "level": 2,
    },
    "body_ache": {
        "bn": ["শরীর ব্যথা", "গা ব্যথা", "সারা শরীরে ব্যথা", "গায়ে ব্যথা"],
        "bl": ["shorir betha", "ga betha", "gaye betha"],
        "en": ["body ache", "body pain", "muscle ache"],
        "specialty": "General Medicine", "level": 1,
    },
    "weakness": {
        "bn": ["দুর্বল লাগছে", "দুর্বলতা", "শরীর দুর্বল", "ক্লান্ত লাগে"],
        "bl": ["durbol lagche", "shorir durbol", "weakness"],
        "en": ["weakness", "fatigue", "feeling very weak", "tired all the time"],
        "specialty": "General Medicine", "level": 2,
    },
    "rash": {
        "bn": ["ফুসকুড়ি", "র‍্যাশ", "চামড়ায় লাল দানা", "গায়ে দানা"],
        "bl": ["rash", "gaye dana", "fuskuri"],
        "en": ["rash", "skin rash", "red spots on skin"],
        "specialty": "Dermatology", "level": 2,
    },
    "itching": {
        "bn": ["চুলকানি", "চুলকাচ্ছে", "গা চুলকায়"],
        "bl": ["chulkani", "chulkacche"],
        "en": ["itching", "itchy skin"],
        "specialty": "Dermatology", "level": 1,
    },
    "blurred_vision": {
        "bn": ["চোখে ঝাপসা দেখছি", "ঝাপসা দেখা", "চোখে কম দেখছি"],
        "bl": ["chokhe jhapsa", "jhapsa dekhi"],
        "en": ["blurred vision", "blurry eyesight", "cant see clearly"],
        "specialty": "Ophthalmology", "level": 3,
    },
    "eye_pain": {
        "bn": ["চোখ ব্যথা", "চোখে ব্যথা", "চোখ লাল"],
        "bl": ["chokh betha", "chokh lal"],
        "en": ["eye pain", "red eye"],
        "specialty": "Ophthalmology", "level": 2,
    },
    "ear_pain": {
        "bn": ["কানে ব্যথা", "কান ব্যথা", "কান দিয়ে পুঁজ"],
        "bl": ["kane betha", "kan betha"],
        "en": ["ear pain", "ear ache", "ear discharge"],
        "specialty": "ENT", "level": 2,
    },
    "toothache": {
        "bn": ["দাঁতে ব্যথা", "দাঁত ব্যথা", "মাড়ি ফুলে গেছে"],
        "bl": ["date betha", "dat betha"],
        "en": ["toothache", "tooth pain", "swollen gum"],
        "specialty": "Dentistry", "level": 2,
    },
    "unconscious": {
        "bn": ["অজ্ঞান হয়ে গেছে", "অজ্ঞান", "জ্ঞান হারিয়েছে", "অচেতন",
               "সেন্সলেস", "সাড়া দিচ্ছে না", "চেতনা নেই"],
        "bl": ["oggan hoye geche", "oggan hoye gese", "oggan", "ojhgan",
               "senseless", "sara dicche na"],
        "en": ["unconscious", "fainted", "passed out", "not responding"],
        "specialty": "Emergency", "level": 5,
    },
    "seizure": {
        "bn": ["খিঁচুনি", "খিঁচুনি হচ্ছে", "খিচুনি", "মৃগী রোগের মত"],
        "bl": ["khichuni", "khichuni hocche", "khichoni"],
        "en": ["seizure", "convulsions", "fits"],
        "specialty": "Neurology", "level": 5,
    },
    "severe_bleeding": {
        "bn": ["প্রচুর রক্তক্ষরণ", "প্রচণ্ড রক্তপাত", "অতিরিক্ত রক্তপাত",
               "রক্ত বন্ধ হচ্ছে না", "রক্তপাত বন্ধ হচ্ছে না", "অনেক রক্ত পড়ছে",
               "প্রচণ্ড রক্তক্ষরণ"],
        "bl": ["onek rokto porche", "rokto bondho hocche na",
               "prochondo roktopat", "prochur roktopat", "beshi rokto porche"],
        "en": ["heavy bleeding", "bleeding wont stop", "severe bleeding"],
        "specialty": "Emergency", "level": 5,
    },
    "stiff_neck": {
        "bn": ["ঘাড় শক্ত হয়ে গেছে", "ঘাড় শক্ত", "ঘাড় নাড়াতে পারছি না",
               "ঘাড় ব্যথা ও শক্ত"],
        "bl": ["ghar shokto", "ghar narate parchi na", "ghaar shokto"],
        "en": ["stiff neck", "neck stiffness", "cant move neck"],
        "specialty": "Neurology", "level": 4,
    },
    "facial_droop": {
        "bn": ["মুখ বেঁকে গেছে", "মুখ বেঁকে যাচ্ছে", "মুখের এক পাশ বেঁকে গেছে"],
        "bl": ["mukh beke geche", "mukh beke gese"],
        "en": ["facial drooping", "face drooping one side", "mouth bent"],
        "specialty": "Neurology", "level": 5,
    },
    "slurred_speech": {
        "bn": ["কথা জড়িয়ে যাচ্ছে", "কথা জড়ানো", "কথা বলতে পারছে না",
               "কথা আটকে যাচ্ছে"],
        "bl": ["kotha joriye jacche", "kotha jorano", "kotha bolte parche na"],
        "en": ["slurred speech", "cannot speak properly", "speech difficulty"],
        "specialty": "Neurology", "level": 5,
    },
    "one_sided_numbness": {
        "bn": ["শরীরের এক পাশ অবশ", "এক পাশ অবশ", "হাত-পা অবশ হয়ে গেছে",
               "এক পাশ দুর্বল", "এক দিক অবশ"],
        "bl": ["ek pash obosh", "ek pash osar", "hat pa obosh"],
        "en": ["numbness one side of body", "one side weak", "arm and leg numb"],
        "specialty": "Neurology", "level": 5,
    },
    "pregnancy_bleeding": {
        "bn": ["গর্ভাবস্থায় রক্তপাত", "গর্ভবতী অবস্থায় রক্তপাত",
               "গর্ভবতী অবস্থায় রক্ত", "প্রেগন্যান্সিতে ব্লিডিং",
               "গর্ভাবস্থায় রক্তক্ষরণ"],
        "bl": ["pregnancy te bleeding", "gorbhaboshthay roktopat",
               "gorbhoboti obosthay roktopat"],
        "en": ["bleeding during pregnancy", "pregnant and bleeding"],
        "specialty": "Gynaecology & Obstetrics", "level": 5,
    },
    "pregnancy_pain": {
        "bn": ["গর্ভাবস্থায় পেটে ব্যথা", "প্রেগন্যান্ট অবস্থায় ব্যথা"],
        "bl": ["pregnant obosthay pet betha"],
        "en": ["abdominal pain during pregnancy", "pregnant with pain"],
        "specialty": "Gynaecology & Obstetrics", "level": 4,
    },
    "missed_period": {
        "bn": ["মাসিক বন্ধ", "পিরিয়ড মিস", "মাসিক অনিয়মিত"],
        "bl": ["period miss", "mashik bondho", "period off"],
        "en": ["missed period", "irregular periods"],
        "specialty": "Gynaecology & Obstetrics", "level": 2,
    },
    "low_mood": {
        "bn": ["মন খারাপ থাকে", "কিছু ভালো লাগে না", "সারাক্ষণ দুশ্চিন্তা", "ঘুম হয় না"],
        "bl": ["mon kharap", "ghum hoy na", "tension e thaki"],
        "en": ["feeling low", "anxious all the time", "cannot sleep", "no interest in anything"],
        "specialty": "Psychiatry", "level": 2,
    },
    "weight_loss": {
        "bn": ["ওজন কমে যাচ্ছে", "শুকিয়ে যাচ্ছি"],
        "bl": ["ojon kome jacche", "weight loss hocche"],
        "en": ["losing weight", "unexplained weight loss"],
        "specialty": "General Medicine", "level": 3,
    },
    "night_sweats": {
        "bn": ["রাতে ঘাম হয়", "রাতে ঘেমে যাই"],
        "bl": ["rate gham hoy"],
        "en": ["night sweats", "sweating at night"],
        "specialty": "Pulmonology", "level": 3,
    },
    "snake_bite": {
        "bn": ["সাপে কামড়েছে", "সাপে কাটা", "সাপে কামড়", "সাপে ধরেছে"],
        "bl": ["shape kamor", "shape kamreche", "sape kamor", "snake e kamor"],
        "en": ["snake bite", "bitten by snake"],
        "specialty": "Emergency", "level": 5,
    },
    "dog_bite": {
        "bn": ["কুকুরে কামড়েছে", "কুকুরের কামড়", "বিড়াল আঁচড় দিয়েছে"],
        "bl": ["kukur kamor diyeche", "dog bite"],
        "en": ["dog bite", "bitten by dog", "cat scratch"],
        "specialty": "General Medicine", "level": 3,
    },
    "burn_injury": {
        "bn": ["পুড়ে গেছে", "গরম পানিতে পুড়েছে", "আগুনে পোড়া"],
        "bl": ["pure geche", "gorom panite pureche"],
        "en": ["burn injury", "burnt by hot water", "fire burn"],
        "specialty": "Emergency", "level": 4,
    },
    "accident_injury": {
        "bn": ["এক্সিডেন্ট করেছে", "আঘাত পেয়েছি", "পড়ে গিয়ে ব্যথা পেয়েছি"],
        "bl": ["accident koreche", "aghat peyechi", "pore giye betha"],
        "en": ["road accident", "injured in accident", "fell and got hurt"],
        "specialty": "Emergency", "level": 4,
    },
    "swelling_legs": {
        "bn": ["পা ফুলে গেছে", "পায়ে পানি এসেছে"],
        "bl": ["pa fule geche", "pa e pani"],
        "en": ["swollen legs", "leg swelling", "water in legs"],
        "specialty": "Nephrology", "level": 3,
    },
    "jaundice": {
        "bn": ["জন্ডিস", "চোখ হলুদ হয়ে গেছে", "প্রস্রাব হলুদ"],
        "bl": ["jondish", "chokh holud"],
        "en": ["jaundice", "yellow eyes", "yellowish skin"],
        "specialty": "Gastroenterology", "level": 3,
    },
    "diabetes_symptoms": {
        "bn": ["ঘন ঘন প্রস্রাব", "খুব পিপাসা লাগে", "ডায়াবেটিস বেড়ে গেছে"],
        "bl": ["ghono ghono prosrab", "khub pipasha", "sugar bere geche"],
        "en": ["frequent urination", "excessive thirst", "sugar level high"],
        "specialty": "Endocrinology", "level": 3,
    },
    "high_bp": {
        "bn": ["প্রেসার বেড়ে গেছে", "উচ্চ রক্তচাপ", "প্রেসার হাই"],
        "bl": ["pressure high", "pressure bere geche"],
        "en": ["high blood pressure", "bp is high"],
        "specialty": "Cardiology", "level": 3,
    },
    "fatigue": {
        "bn": ["খুব ক্লান্ত লাগে", "শরীর দুর্বল লাগে", "কোনো শক্তি পাই না",
               "ক্লান্তি"],
        "bl": ["khub klanto lage", "shorir durbol", "energy nai", "klanti"],
        "en": ["fatigue", "always tired", "feeling exhausted", "no energy"],
        "specialty": "General Medicine", "level": 2,
    },
    "insomnia": {
        "bn": ["ঘুম হচ্ছে না", "রাতে ঘুম আসে না", "অনিদ্রা"],
        "bl": ["ghum hocche na", "rate ghum ase na", "onidra"],
        "en": ["insomnia", "cannot sleep", "trouble sleeping", "sleepless"],
        "specialty": "Psychiatry", "level": 2,
    },
    "anxiety": {
        "bn": ["খুব দুশ্চিন্তা হয়", "অস্থির লাগে", "মন ছটফট করে", "উদ্বেগ"],
        "bl": ["khub duschinta", "osthir lage", "tension hocche"],
        "en": ["anxiety", "feeling anxious", "restless", "panic feeling"],
        "specialty": "Psychiatry", "level": 2,
    },
    "skin_rash": {
        "bn": ["চামড়ায় র‍্যাশ", "গায়ে দাগ", "চুলকানি সহ র‍্যাশ"],
        "bl": ["chamray rash", "gaye dag", "rash uthche"],
        "en": ["skin rash", "rashes on skin", "red spots on skin"],
        "specialty": "Dermatology", "level": 2,
    },
    "swelling": {
        "bn": ["ফুলে গেছে", "শরীর ফুলে যাচ্ছে", "পানি জমেছে"],
        "bl": ["fule geche", "shorir fule jacche"],
        "en": ["swelling", "body swelling", "fluid retention"],
        "specialty": "Nephrology", "level": 3,
    },
    "frequent_urination": {
        "bn": ["ঘন ঘন প্রস্রাবের বেগ", "বারবার বাথরুমে যেতে হয়"],
        "bl": ["ghono ghono prosrab hoy", "barbar bathroom"],
        "en": ["urinating frequently", "passing urine often"],
        "specialty": "Endocrinology", "level": 3,
    },
    "excessive_thirst": {
        "bn": ["খুব পিপাসা পায়", "সারাক্ষণ পানি খেতে ইচ্ছা করে"],
        "bl": ["khub pipasa pay", "shobshomoy pani khete iccha"],
        "en": ["excessive thirst", "always thirsty", "drinking a lot of water"],
        "specialty": "Endocrinology", "level": 3,
    },
}
