# -*- coding: utf-8 -*-
"""Build the drug-safety knowledge base.

Two tables are produced:

``bd_brand_aliases.csv``
    Bangladeshi brand name -> generic (INN) name. Brand-first prescribing is
    the norm in Bangladesh, so interaction checking is useless unless brands
    resolve to generics first: a prescription reading "Napa" and "Ace" is two
    brands of the same paracetamol and must be caught as duplicate therapy.

``drug_interactions.csv``
    Generic-pair interactions with severity and bilingual counselling advice.

Scope is stated plainly in the model card: this is a curated set covering the
interactions most likely to appear in Bangladeshi outpatient prescribing, not
an exhaustive pharmacopoeia. It is a screening aid for a prescriber, never a
substitute for one.

Output: data/drugs/bd_brand_aliases.csv, data/drugs/drug_interactions.csv
"""
from __future__ import annotations

import csv
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "data" / "drugs"

# Brand -> generic. Brands are the leading Bangladeshi trade names from
# Square, Beximco, Incepta, Renata, ACI, Opsonin, Eskayef and Aristopharma.
BRANDS = [
    ("napa", "paracetamol"),
    ("ace", "paracetamol"),
    ("fast", "paracetamol"),
    ("renova", "paracetamol"),
    ("xpa", "paracetamol"),
    ("paracet", "paracetamol"),
    ("seclo", "omeprazole"),
    ("losectil", "omeprazole"),
    ("omep", "omeprazole"),
    ("pantonix", "pantoprazole"),
    ("panto", "pantoprazole"),
    ("maxpro", "esomeprazole"),
    ("nexum", "esomeprazole"),
    ("sergel", "esomeprazole"),
    ("finix", "esomeprazole"),
    ("rabe", "rabeprazole"),
    ("clopid", "clopidogrel"),
    ("plavix", "clopidogrel"),
    ("ecosprin", "aspirin"),
    ("aspirin", "aspirin"),
    ("disprin", "aspirin"),
    ("cardiprin", "aspirin"),
    ("warfin", "warfarin"),
    ("warf", "warfarin"),
    ("xarelto", "rivaroxaban"),
    ("rivarox", "rivaroxaban"),
    ("monas", "montelukast"),
    ("montene", "montelukast"),
    ("azithrocin", "azithromycin"),
    ("zimax", "azithromycin"),
    ("azin", "azithromycin"),
    ("cef-3", "ceftriaxone"),
    ("ceftron", "ceftriaxone"),
    ("cefixime", "cefixime"),
    ("cef-a", "cefixime"),
    ("amoxil", "amoxicillin"),
    ("moxacil", "amoxicillin"),
    ("fimoxyl", "amoxicillin"),
    ("ciprocin", "ciprofloxacin"),
    ("cipro-a", "ciprofloxacin"),
    ("neofloxin", "ciprofloxacin"),
    ("levoflox", "levofloxacin"),
    ("levox", "levofloxacin"),
    ("flagyl", "metronidazole"),
    ("amodis", "metronidazole"),
    ("filmet", "metronidazole"),
    ("doxicap", "doxycycline"),
    ("doxin", "doxycycline"),
    ("metfo", "metformin"),
    ("comet", "metformin"),
    ("glucophage", "metformin"),
    ("bigmet", "metformin"),
    ("diamicron", "gliclazide"),
    ("comprid", "glimepiride"),
    ("amaryl", "glimepiride"),
    ("secrin", "glimepiride"),
    ("januvia", "sitagliptin"),
    ("sitagen", "sitagliptin"),
    ("losartan", "losartan"),
    ("losatan", "losartan"),
    ("angilock", "losartan"),
    ("amlodipin", "amlodipine"),
    ("amdocal", "amlodipine"),
    ("camlodin", "amlodipine"),
    ("atenolol", "atenolol"),
    ("cardipro", "atenolol"),
    ("bisocard", "bisoprolol"),
    ("prohibit", "ramipril"),
    ("ramipril", "ramipril"),
    ("enalapril", "enalapril"),
    ("lasix", "furosemide"),
    ("frusemide", "furosemide"),
    ("indever", "propranolol"),
    ("atova", "atorvastatin"),
    ("lipitor", "atorvastatin"),
    ("atorva", "atorvastatin"),
    ("rosuva", "rosuvastatin"),
    ("crestor", "rosuvastatin"),
    ("simva", "simvastatin"),
    ("alatrol", "cetirizine"),
    ("cetizin", "cetirizine"),
    ("fexo", "fexofenadine"),
    ("fenadin", "fexofenadine"),
    ("deslor", "desloratadine"),
    ("encilor", "loratadine"),
    ("tufnil", "tolfenamic acid"),
    ("napa extra", "paracetamol"),
    ("etorix", "etoricoxib"),
    ("torix", "etoricoxib"),
    ("naprox", "naproxen"),
    ("anaflex", "naproxen"),
    ("diclofen", "diclofenac"),
    ("voltalin", "diclofenac"),
    ("clofenac", "diclofenac"),
    ("ibufen", "ibuprofen"),
    ("flamex", "ibuprofen"),
    ("profen", "ibuprofen"),
    ("indomet", "indomethacin"),
    ("ketorol", "ketorolac"),
    ("deltasone", "prednisolone"),
    ("cortan", "prednisolone"),
    ("predsol", "prednisolone"),
    ("dexa", "dexamethasone"),
    ("oradexon", "dexamethasone"),
    ("thyrox", "levothyroxine"),
    ("eltroxin", "levothyroxine"),
    ("thyrin", "levothyroxine"),
    ("sedil", "diazepam"),
    ("easium", "diazepam"),
    ("epival", "sodium valproate"),
    ("valpro", "sodium valproate"),
    ("carbatol", "carbamazepine"),
    ("tegretol", "carbamazepine"),
    ("epilep", "phenytoin"),
    ("dilantin", "phenytoin"),
    ("sertral", "sertraline"),
    ("zoloft", "sertraline"),
    ("fludac", "fluoxetine"),
    ("prodep", "fluoxetine"),
    ("amitryn", "amitriptyline"),
    ("tramadol", "tramadol"),
    ("tramax", "tramadol"),
    ("morphine", "morphine"),
    ("sildenafil", "sildenafil"),
    ("nitrocard", "glyceryl trinitrate"),
    ("angised", "glyceryl trinitrate"),
    ("isordil", "isosorbide dinitrate"),
    ("digoxin", "digoxin"),
    ("lanoxin", "digoxin"),
    ("theophylline", "theophylline"),
    ("clarithro", "clarithromycin"),
    ("klaricid", "clarithromycin"),
    ("fluconazole", "fluconazole"),
    ("flugal", "fluconazole"),
    ("ketoconazole", "ketoconazole"),
    ("allopurinol", "allopurinol"),
    ("zyloric", "allopurinol"),
    ("colchicine", "colchicine"),
    ("spiro", "spironolactone"),
    ("aldactone", "spironolactone"),
    ("rifampicin", "rifampicin"),
    ("isoniazid", "isoniazid"),
    ("salbutamol", "salbutamol"),
    ("ventolin", "salbutamol"),
    ("montair", "montelukast"),
    ("ranitidine", "ranitidine"),
    ("neotack", "ranitidine"),
    ("ondansetron", "ondansetron"),
    ("emistat", "ondansetron"),
    ("domperidone", "domperidone"),
    ("omidon", "domperidone"),
    ("motigut", "domperidone"),
]

# (drug_a, drug_b, severity, effect_en, effect_bn, advice_en, advice_bn)
INTERACTIONS = [
    ("warfarin", "aspirin", "major",
     "Greatly increased risk of serious bleeding",
     "মারাত্মক রক্তক্ষরণের ঝুঁকি অনেক বেড়ে যায়",
     "Avoid unless a specialist has weighed the risk. Monitor INR and watch for bleeding.",
     "বিশেষজ্ঞের পরামর্শ ছাড়া একসাথে দেবেন না। INR পরীক্ষা ও রক্তক্ষরণ লক্ষ্য রাখুন।"),
    ("warfarin", "clopidogrel", "major",
     "Additive bleeding risk",
     "রক্তক্ষরণের ঝুঁকি বহুগুণ বাড়ে",
     "Combination needs specialist supervision and close INR monitoring.",
     "বিশেষজ্ঞের তত্ত্বাবধান ও নিয়মিত INR পরীক্ষা প্রয়োজন।"),
    ("warfarin", "ciprofloxacin", "major",
     "Ciprofloxacin raises warfarin levels and INR",
     "সিপ্রোফ্লক্সাসিন ওয়ারফারিনের মাত্রা ও INR বাড়িয়ে দেয়",
     "Choose another antibiotic if possible; otherwise check INR within 3 days.",
     "সম্ভব হলে অন্য অ্যান্টিবায়োটিক দিন; নয়তো ৩ দিনের মধ্যে INR দেখুন।"),
    ("warfarin", "metronidazole", "major",
     "Metronidazole markedly potentiates warfarin",
     "মেট্রোনিডাজল ওয়ারফারিনের কার্যকারিতা অনেক বাড়ায়",
     "Avoid together where possible; reduce warfarin dose and monitor INR.",
     "সম্ভব হলে একসাথে দেবেন না; ওয়ারফারিনের ডোজ কমিয়ে INR দেখুন।"),
    ("warfarin", "fluconazole", "major",
     "Fluconazole inhibits warfarin metabolism, raising INR",
     "ফ্লুকোনাজল ওয়ারফারিনের বিপাক কমিয়ে INR বাড়ায়",
     "Use the lowest antifungal dose and monitor INR closely.",
     "সবচেয়ে কম ডোজে অ্যান্টিফাঙ্গাল দিন এবং INR নিবিড়ভাবে দেখুন।"),
    ("warfarin", "diclofenac", "major",
     "NSAID plus anticoagulant causes gastrointestinal bleeding",
     "এনএসএআইডি ও রক্ত পাতলা করার ওষুধ একসাথে পাকস্থলীতে রক্তক্ষরণ ঘটায়",
     "Use paracetamol for pain instead of an NSAID.",
     "ব্যথার জন্য এনএসএআইডির বদলে প্যারাসিটামল ব্যবহার করুন।"),
    ("warfarin", "ibuprofen", "major",
     "NSAID plus anticoagulant causes gastrointestinal bleeding",
     "এনএসএআইডি ও রক্ত পাতলা করার ওষুধ একসাথে রক্তক্ষরণ ঘটায়",
     "Prefer paracetamol; if an NSAID is unavoidable add gastric protection.",
     "প্যারাসিটামল দিন; এনএসএআইডি লাগলে গ্যাস্ট্রিক সুরক্ষা যোগ করুন।"),
    ("warfarin", "naproxen", "major",
     "Additive bleeding risk with NSAID",
     "এনএসএআইডির সাথে রক্তক্ষরণের ঝুঁকি বাড়ে",
     "Avoid; substitute paracetamol.",
     "এড়িয়ে চলুন; বদলে প্যারাসিটামল দিন।"),
    ("warfarin", "levothyroxine", "moderate",
     "Thyroid hormone enhances warfarin effect",
     "থাইরয়েড হরমোন ওয়ারফারিনের প্রভাব বাড়ায়",
     "Recheck INR after any levothyroxine dose change.",
     "লেভোথাইরক্সিনের ডোজ বদলালে INR আবার দেখুন।"),
    ("aspirin", "clopidogrel", "moderate",
     "Dual antiplatelet therapy increases bleeding risk",
     "দুটি অ্যান্টিপ্লেটলেট একসাথে রক্তক্ষরণের ঝুঁকি বাড়ায়",
     "Intentional after stenting, but confirm the indication and duration.",
     "স্টেন্টের পরে ইচ্ছাকৃত হতে পারে; কারণ ও মেয়াদ নিশ্চিত করুন।"),
    ("aspirin", "ibuprofen", "moderate",
     "Ibuprofen blocks the cardioprotective effect of aspirin",
     "আইবুপ্রোফেন অ্যাসপিরিনের হৃদরোগ প্রতিরোধী প্রভাব নষ্ট করে",
     "Take aspirin at least 2 hours before ibuprofen.",
     "আইবুপ্রোফেনের অন্তত ২ ঘণ্টা আগে অ্যাসপিরিন নিন।"),
    ("aspirin", "diclofenac", "major",
     "Two NSAIDs together sharply raise ulcer and bleeding risk",
     "দুটি এনএসএআইডি একসাথে আলসার ও রক্তক্ষরণের ঝুঁকি বাড়ায়",
     "Do not combine. Use one NSAID only.",
     "একসাথে দেবেন না। যেকোনো একটি এনএসএআইডি দিন।"),
    ("aspirin", "naproxen", "major",
     "Duplicate NSAID therapy",
     "একই ধরনের দুটি এনএসএআইডি",
     "Do not combine; choose a single agent.",
     "একসাথে দেবেন না; একটি বেছে নিন।"),
    ("ibuprofen", "diclofenac", "major",
     "Duplicate NSAID therapy with no added benefit",
     "একই শ্রেণির দুটি ওষুধ, বাড়তি উপকার নেই",
     "Prescribe only one NSAID.",
     "শুধু একটি এনএসএআইডি দিন।"),
    ("ibuprofen", "naproxen", "major",
     "Duplicate NSAID therapy",
     "একই শ্রেণির দুটি এনএসএআইডি",
     "Prescribe only one NSAID.",
     "শুধু একটি এনএসএআইডি দিন।"),
    ("diclofenac", "naproxen", "major",
     "Duplicate NSAID therapy",
     "একই শ্রেণির দুটি এনএসএআইডি",
     "Prescribe only one NSAID.",
     "শুধু একটি এনএসএআইডি দিন।"),
    ("diclofenac", "etoricoxib", "major",
     "Duplicate NSAID therapy",
     "একই শ্রেণির দুটি এনএসএআইডি",
     "Prescribe only one NSAID.",
     "শুধু একটি এনএসএআইডি দিন।"),
    ("ibuprofen", "ketorolac", "major",
     "Duplicate NSAID therapy with high ulcer risk",
     "উচ্চ আলসার ঝুঁকিসহ একই শ্রেণির দুটি ওষুধ",
     "Do not combine.",
     "একসাথে দেবেন না।"),
    ("diclofenac", "ramipril", "moderate",
     "NSAIDs blunt ACE inhibitor effect and may impair kidney function",
     "এনএসএআইডি রক্তচাপের ওষুধের কার্যকারিতা কমায় ও কিডনির ক্ষতি করতে পারে",
     "Monitor blood pressure and creatinine; keep NSAID courses short.",
     "রক্তচাপ ও ক্রিয়েটিনিন দেখুন; এনএসএআইডি অল্প দিনের জন্য দিন।"),
    ("ibuprofen", "ramipril", "moderate",
     "Reduced antihypertensive effect and renal risk",
     "রক্তচাপ নিয়ন্ত্রণ কমে ও কিডনির ঝুঁকি বাড়ে",
     "Monitor blood pressure and kidney function.",
     "রক্তচাপ ও কিডনির অবস্থা পর্যবেক্ষণ করুন।"),
    ("diclofenac", "losartan", "moderate",
     "NSAID reduces the effect of the angiotensin receptor blocker",
     "এনএসএআইডি রক্তচাপের ওষুধের কার্যকারিতা কমায়",
     "Monitor blood pressure; avoid prolonged NSAID use.",
     "রক্তচাপ দেখুন; দীর্ঘদিন এনএসএআইডি দেবেন না।"),
    ("ibuprofen", "furosemide", "moderate",
     "NSAIDs reduce diuretic efficacy and can worsen kidney function",
     "এনএসএআইডি প্রস্রাবের ওষুধের কাজ কমায় ও কিডনির ক্ষতি করে",
     "Monitor weight, oedema and creatinine.",
     "ওজন, পানি জমা ও ক্রিয়েটিনিন দেখুন।"),
    ("ramipril", "spironolactone", "major",
     "Risk of dangerous hyperkalaemia",
     "রক্তে পটাসিয়াম বিপজ্জনকভাবে বেড়ে যাওয়ার ঝুঁকি",
     "Check serum potassium within one week and then regularly.",
     "এক সপ্তাহের মধ্যে ও পরে নিয়মিত পটাসিয়াম পরীক্ষা করুন।"),
    ("losartan", "spironolactone", "major",
     "Additive hyperkalaemia risk",
     "পটাসিয়াম বেড়ে যাওয়ার ঝুঁকি বাড়ে",
     "Monitor serum potassium and renal function.",
     "পটাসিয়াম ও কিডনির অবস্থা পর্যবেক্ষণ করুন।"),
    ("ramipril", "enalapril", "major",
     "Duplicate ACE inhibitor therapy",
     "একই শ্রেণির দুটি ওষুধ",
     "Prescribe only one ACE inhibitor.",
     "শুধু একটি ওষুধ দিন।"),
    ("ramipril", "losartan", "moderate",
     "Dual renin-angiotensin blockade increases renal and potassium risk",
     "দুটি একই ধরনের ওষুধ কিডনি ও পটাসিয়ামের ঝুঁকি বাড়ায়",
     "Generally avoid combining these two classes.",
     "সাধারণত এই দুটি একসাথে দেবেন না।"),
    ("atenolol", "verapamil", "major",
     "Risk of severe bradycardia and heart block",
     "হৃদস্পন্দন বিপজ্জনকভাবে কমে যেতে পারে",
     "Avoid; if essential, monitor heart rate and ECG.",
     "এড়িয়ে চলুন; প্রয়োজনে হৃদস্পন্দন ও ইসিজি দেখুন।"),
    ("atenolol", "salbutamol", "moderate",
     "Beta blocker opposes the bronchodilator and can worsen asthma",
     "বিটা ব্লকার শ্বাসনালী প্রসারক ওষুধের কাজ বাধা দেয়",
     "Prefer a cardioselective agent; avoid in asthma.",
     "হাঁপানিতে এড়িয়ে চলুন; কার্ডিওসিলেক্টিভ ওষুধ দিন।"),
    ("propranolol", "salbutamol", "major",
     "Non-selective beta blockade can trigger bronchospasm",
     "এই বিটা ব্লকার হাঁপানির টান তুলতে পারে",
     "Contraindicated in asthma; choose another agent.",
     "হাঁপানিতে নিষিদ্ধ; অন্য ওষুধ দিন।"),
    ("digoxin", "furosemide", "moderate",
     "Diuretic-induced low potassium increases digoxin toxicity",
     "পটাসিয়াম কমে গেলে ডিগক্সিনের বিষক্রিয়া বাড়ে",
     "Monitor potassium and watch for nausea or visual changes.",
     "পটাসিয়াম দেখুন; বমিভাব বা দৃষ্টি সমস্যা লক্ষ্য করুন।"),
    ("digoxin", "clarithromycin", "major",
     "Clarithromycin raises digoxin levels toward toxicity",
     "ক্ল্যারিথ্রোমাইসিন ডিগক্সিনের মাত্রা বিষাক্ত পর্যায়ে নিতে পারে",
     "Avoid or reduce digoxin dose with level monitoring.",
     "এড়িয়ে চলুন বা ডোজ কমিয়ে মাত্রা পরীক্ষা করুন।"),
    ("digoxin", "spironolactone", "moderate",
     "Spironolactone increases digoxin concentration",
     "স্পাইরোনোল্যাকটোন ডিগক্সিনের মাত্রা বাড়ায়",
     "Monitor digoxin level and potassium.",
     "ডিগক্সিনের মাত্রা ও পটাসিয়াম দেখুন।"),
    ("atorvastatin", "clarithromycin", "major",
     "Sharply increased risk of muscle breakdown",
     "মাংসপেশি ভেঙে যাওয়ার ঝুঁকি অনেক বাড়ে",
     "Suspend the statin during the antibiotic course.",
     "অ্যান্টিবায়োটিক চলাকালীন স্ট্যাটিন বন্ধ রাখুন।"),
    ("simvastatin", "clarithromycin", "major",
     "Contraindicated: high rhabdomyolysis risk",
     "নিষিদ্ধ সমন্বয়: মাংসপেশি ভাঙার উচ্চ ঝুঁকি",
     "Do not combine. Stop the statin or choose another antibiotic.",
     "একসাথে দেবেন না। স্ট্যাটিন বন্ধ করুন বা অন্য অ্যান্টিবায়োটিক দিন।"),
    ("atorvastatin", "fluconazole", "moderate",
     "Raised statin exposure and myopathy risk",
     "স্ট্যাটিনের মাত্রা বেড়ে পেশির সমস্যা হতে পারে",
     "Watch for muscle pain; consider a lower statin dose.",
     "পেশিতে ব্যথা লক্ষ্য করুন; ডোজ কমানোর কথা ভাবুন।"),
    ("atorvastatin", "colchicine", "moderate",
     "Additive myopathy risk",
     "পেশির ক্ষতির ঝুঁকি বাড়ে",
     "Advise the patient to report muscle pain or dark urine.",
     "পেশিতে ব্যথা বা গাঢ় প্রস্রাব হলে জানাতে বলুন।"),
    ("metformin", "furosemide", "moderate",
     "Dehydration raises the risk of lactic acidosis",
     "পানিশূন্যতায় ল্যাকটিক অ্যাসিডোসিসের ঝুঁকি বাড়ে",
     "Ensure hydration and monitor renal function.",
     "পর্যাপ্ত পানি ও কিডনি পরীক্ষা নিশ্চিত করুন।"),
    ("metformin", "prednisolone", "moderate",
     "Steroids raise blood glucose and oppose metformin",
     "স্টেরয়েড রক্তে সুগার বাড়িয়ে দেয়",
     "Monitor glucose more frequently during steroid therapy.",
     "স্টেরয়েড চলাকালীন ঘন ঘন সুগার পরীক্ষা করুন।"),
    ("glimepiride", "ciprofloxacin", "moderate",
     "Fluoroquinolones can cause severe hypoglycaemia with sulfonylureas",
     "এই অ্যান্টিবায়োটিক সুগার বিপজ্জনকভাবে কমাতে পারে",
     "Warn the patient about hypoglycaemia and monitor glucose.",
     "সুগার কমার লক্ষণ সম্পর্কে সতর্ক করুন ও পরীক্ষা করুন।"),
    ("glimepiride", "gliclazide", "major",
     "Duplicate sulfonylurea therapy causing hypoglycaemia",
     "একই শ্রেণির দুটি ওষুধ, সুগার বিপজ্জনকভাবে কমতে পারে",
     "Prescribe only one sulfonylurea.",
     "শুধু একটি ওষুধ দিন।"),
    ("prednisolone", "diclofenac", "major",
     "Steroid plus NSAID greatly increases peptic ulcer risk",
     "স্টেরয়েড ও এনএসএআইডি একসাথে আলসারের ঝুঁকি অনেক বাড়ায়",
     "Add gastric protection and keep the course as short as possible.",
     "গ্যাস্ট্রিক সুরক্ষা দিন ও কম দিনের জন্য চালান।"),
    ("prednisolone", "ibuprofen", "major",
     "Increased gastrointestinal ulceration and bleeding",
     "পাকস্থলীতে ঘা ও রক্তক্ষরণের ঝুঁকি বাড়ে",
     "Co-prescribe a proton pump inhibitor if unavoidable.",
     "অপরিহার্য হলে সাথে গ্যাস্ট্রিকের ওষুধ দিন।"),
    ("omeprazole", "clopidogrel", "major",
     "Omeprazole reduces the antiplatelet effect of clopidogrel",
     "ওমিপ্রাজল ক্লোপিডোগ্রেলের কার্যকারিতা কমিয়ে দেয়",
     "Switch to pantoprazole, which does not interact.",
     "প্যান্টোপ্রাজলে পরিবর্তন করুন, এতে সমস্যা নেই।"),
    ("esomeprazole", "clopidogrel", "major",
     "Reduced clopidogrel activation",
     "ক্লোপিডোগ্রেলের কার্যকারিতা কমে যায়",
     "Prefer pantoprazole with clopidogrel.",
     "ক্লোপিডোগ্রেলের সাথে প্যান্টোপ্রাজল দিন।"),
    ("omeprazole", "esomeprazole", "moderate",
     "Duplicate proton pump inhibitor therapy",
     "একই শ্রেণির দুটি গ্যাস্ট্রিকের ওষুধ",
     "Prescribe only one proton pump inhibitor.",
     "শুধু একটি ওষুধ দিন।"),
    ("omeprazole", "pantoprazole", "moderate",
     "Duplicate proton pump inhibitor therapy",
     "একই শ্রেণির দুটি গ্যাস্ট্রিকের ওষুধ",
     "Prescribe only one proton pump inhibitor.",
     "শুধু একটি ওষুধ দিন।"),
    ("ciprofloxacin", "theophylline", "major",
     "Ciprofloxacin raises theophylline to toxic levels",
     "সিপ্রোফ্লক্সাসিন থিওফাইলিনের মাত্রা বিষাক্ত করে তোলে",
     "Avoid the combination; choose a different antibiotic.",
     "এই সমন্বয় এড়িয়ে চলুন; অন্য অ্যান্টিবায়োটিক দিন।"),
    ("ciprofloxacin", "tizanidine", "major",
     "Severe hypotension and sedation",
     "রক্তচাপ বিপজ্জনকভাবে কমে ও তন্দ্রা আসে",
     "Contraindicated; select another antibiotic.",
     "নিষিদ্ধ; অন্য অ্যান্টিবায়োটিক দিন।"),
    ("levofloxacin", "ondansetron", "moderate",
     "Additive QT prolongation",
     "হৃদস্পন্দনের ছন্দে সমস্যা হতে পারে",
     "Avoid in patients with cardiac disease or electrolyte disturbance.",
     "হৃদরোগ বা লবণের ভারসাম্যহীনতা থাকলে এড়িয়ে চলুন।"),
    ("azithromycin", "ondansetron", "moderate",
     "Additive QT prolongation",
     "হৃদস্পন্দনের ছন্দে সমস্যার ঝুঁকি",
     "Check potassium and magnesium; avoid in known QT prolongation.",
     "পটাসিয়াম ও ম্যাগনেসিয়াম দেখুন; ঝুঁকি থাকলে এড়িয়ে চলুন।"),
    ("azithromycin", "clarithromycin", "moderate",
     "Duplicate macrolide therapy",
     "একই শ্রেণির দুটি অ্যান্টিবায়োটিক",
     "Prescribe only one macrolide.",
     "শুধু একটি অ্যান্টিবায়োটিক দিন।"),
    ("metronidazole", "alcohol", "major",
     "Disulfiram-like reaction with severe vomiting",
     "তীব্র বমি ও অস্বস্তি হতে পারে",
     "Avoid alcohol during and for 48 hours after the course.",
     "চিকিৎসা চলাকালীন ও পরের ৪৮ ঘণ্টা অ্যালকোহল নিষেধ।"),
    ("doxycycline", "ferrous sulphate", "moderate",
     "Iron binds doxycycline and blocks absorption",
     "আয়রন ডক্সিসাইক্লিনের শোষণে বাধা দেয়",
     "Separate the two doses by at least 2 hours.",
     "দুটি ওষুধের মধ্যে অন্তত ২ ঘণ্টা ব্যবধান রাখুন।"),
    ("levothyroxine", "ferrous sulphate", "moderate",
     "Iron reduces levothyroxine absorption",
     "আয়রন থাইরয়েড ওষুধের শোষণ কমায়",
     "Take levothyroxine 4 hours apart from iron.",
     "থাইরয়েডের ওষুধ আয়রন থেকে ৪ ঘণ্টা আলাদা করে নিন।"),
    ("levothyroxine", "omeprazole", "moderate",
     "Reduced levothyroxine absorption",
     "থাইরয়েড ওষুধের শোষণ কমে যায়",
     "Monitor thyroid function after starting the acid suppressant.",
     "গ্যাস্ট্রিকের ওষুধ শুরুর পর থাইরয়েড পরীক্ষা করুন।"),
    ("phenytoin", "carbamazepine", "moderate",
     "Mutual enzyme induction lowers both drug levels",
     "দুটি ওষুধ পরস্পরের মাত্রা কমিয়ে দেয়",
     "Monitor levels and seizure control.",
     "ওষুধের মাত্রা ও খিঁচুনি নিয়ন্ত্রণ পর্যবেক্ষণ করুন।"),
    ("carbamazepine", "clarithromycin", "major",
     "Clarithromycin raises carbamazepine to toxic levels",
     "ক্ল্যারিথ্রোমাইসিন কার্বামাজেপিনের মাত্রা বিষাক্ত করে",
     "Choose a different antibiotic or monitor levels closely.",
     "অন্য অ্যান্টিবায়োটিক দিন বা মাত্রা নিবিড়ভাবে দেখুন।"),
    ("sodium valproate", "carbamazepine", "moderate",
     "Complex interaction altering both levels",
     "দুটি ওষুধের মাত্রা পরস্পরকে প্রভাবিত করে",
     "Specialist supervision with level monitoring is required.",
     "বিশেষজ্ঞের তত্ত্বাবধানে মাত্রা পরীক্ষা প্রয়োজন।"),
    ("sertraline", "tramadol", "major",
     "Serotonin syndrome and lowered seizure threshold",
     "সেরোটোনিন সিনড্রোম ও খিঁচুনির ঝুঁকি",
     "Avoid; if unavoidable, warn about agitation, fever and tremor.",
     "এড়িয়ে চলুন; প্রয়োজনে জ্বর, কাঁপুনি ও অস্থিরতায় সতর্ক থাকুন।"),
    ("fluoxetine", "tramadol", "major",
     "Serotonin syndrome risk",
     "সেরোটোনিন সিনড্রোমের ঝুঁকি",
     "Choose a different analgesic.",
     "অন্য ব্যথানাশক বেছে নিন।"),
    ("sertraline", "fluoxetine", "major",
     "Duplicate SSRI therapy",
     "একই শ্রেণির দুটি ওষুধ",
     "Prescribe only one SSRI.",
     "শুধু একটি ওষুধ দিন।"),
    ("sertraline", "aspirin", "moderate",
     "SSRIs increase gastrointestinal bleeding risk with antiplatelets",
     "এই দুটি একসাথে পাকস্থলীতে রক্তক্ষরণের ঝুঁকি বাড়ায়",
     "Consider gastric protection in older patients.",
     "বয়স্ক রোগীতে গ্যাস্ট্রিক সুরক্ষা বিবেচনা করুন।"),
    ("amitriptyline", "tramadol", "major",
     "Seizure risk and serotonin syndrome",
     "খিঁচুনি ও সেরোটোনিন সিনড্রোমের ঝুঁকি",
     "Avoid the combination.",
     "এই সমন্বয় এড়িয়ে চলুন।"),
    ("diazepam", "tramadol", "major",
     "Additive respiratory depression and sedation",
     "শ্বাস-প্রশ্বাস ধীর হয়ে যাওয়া ও অতিরিক্ত ঘুম",
     "Avoid; if essential use the lowest doses and monitor.",
     "এড়িয়ে চলুন; প্রয়োজনে সর্বনিম্ন ডোজে পর্যবেক্ষণ করুন।"),
    ("diazepam", "morphine", "major",
     "Serious risk of respiratory depression",
     "শ্বাসকষ্টের গুরুতর ঝুঁকি",
     "Avoid outside supervised inpatient settings.",
     "হাসপাতালের তত্ত্বাবধান ছাড়া দেবেন না।"),
    ("sildenafil", "glyceryl trinitrate", "major",
     "Life-threatening fall in blood pressure",
     "রক্তচাপ প্রাণঘাতী মাত্রায় কমে যেতে পারে",
     "Absolutely contraindicated together.",
     "একসাথে সম্পূর্ণ নিষিদ্ধ।"),
    ("sildenafil", "isosorbide dinitrate", "major",
     "Severe hypotension",
     "রক্তচাপ বিপজ্জনকভাবে কমে যায়",
     "Contraindicated; never co-prescribe.",
     "নিষিদ্ধ; কখনো একসাথে দেবেন না।"),
    ("allopurinol", "amoxicillin", "moderate",
     "Increased incidence of skin rash",
     "চামড়ায় র‍্যাশের ঝুঁকি বাড়ে",
     "Warn the patient and review if a rash appears.",
     "রোগীকে সতর্ক করুন; র‍্যাশ হলে পুনরায় দেখান।"),
    ("rifampicin", "warfarin", "major",
     "Rifampicin sharply reduces warfarin effect",
     "রিফামপিসিন ওয়ারফারিনের কার্যকারিতা অনেক কমায়",
     "Expect a large dose increase; monitor INR frequently.",
     "ডোজ বাড়াতে হতে পারে; ঘন ঘন INR দেখুন।"),
    ("rifampicin", "atorvastatin", "moderate",
     "Reduced statin effectiveness",
     "স্ট্যাটিনের কার্যকারিতা কমে যায়",
     "Monitor lipid response during treatment.",
     "চিকিৎসাকালে লিপিড পরীক্ষা করুন।"),
    ("isoniazid", "phenytoin", "major",
     "Isoniazid raises phenytoin to toxic levels",
     "আইসোনিয়াজিড ফেনিটয়েনের মাত্রা বিষাক্ত করে",
     "Monitor phenytoin levels and reduce the dose.",
     "ফেনিটয়েনের মাত্রা দেখে ডোজ কমান।"),
    ("ketoconazole", "omeprazole", "moderate",
     "Acid suppression reduces ketoconazole absorption",
     "গ্যাস্ট্রিকের ওষুধ অ্যান্টিফাঙ্গালের শোষণ কমায়",
     "Separate doses or select a different antifungal.",
     "সময়ের ব্যবধান রাখুন বা অন্য ওষুধ দিন।"),
    ("colchicine", "clarithromycin", "major",
     "Risk of fatal colchicine toxicity",
     "কোলচিসিনের প্রাণঘাতী বিষক্রিয়ার ঝুঁকি",
     "Contraindicated in renal or hepatic impairment.",
     "কিডনি বা লিভারের সমস্যা থাকলে নিষিদ্ধ।"),
    ("paracetamol", "warfarin", "moderate",
     "Regular high-dose paracetamol can raise INR",
     "নিয়মিত বেশি মাত্রার প্যারাসিটামল INR বাড়াতে পারে",
     "Occasional use is safe; monitor INR with sustained use.",
     "মাঝে মাঝে নিরাপদ; নিয়মিত দিলে INR দেখুন।"),
    ("tramadol", "carbamazepine", "moderate",
     "Carbamazepine reduces tramadol analgesic effect",
     "কার্বামাজেপিন ট্রামাডলের ব্যথানাশক প্রভাব কমায়",
     "Consider an alternative analgesic.",
     "বিকল্প ব্যথানাশক বিবেচনা করুন।"),
    ("montelukast", "phenytoin", "moderate",
     "Phenytoin lowers montelukast exposure",
     "ফেনিটয়েন মনটেলুকাস্টের মাত্রা কমায়",
     "Monitor asthma control.",
     "হাঁপানি নিয়ন্ত্রণ পর্যবেক্ষণ করুন।"),
    ("furosemide", "gentamicin", "major",
     "Additive kidney and hearing damage",
     "কিডনি ও শ্রবণশক্তির ক্ষতির ঝুঁকি বাড়ে",
     "Avoid; monitor renal function and hearing if unavoidable.",
     "এড়িয়ে চলুন; প্রয়োজনে কিডনি ও শ্রবণ পরীক্ষা করুন।"),
    ("spironolactone", "furosemide", "minor",
     "Commonly combined; potassium effects offset each other",
     "সাধারণত একসাথে দেওয়া হয়; পটাসিয়ামের প্রভাব ভারসাম্য রাখে",
     "Intentional combination, but still check potassium.",
     "ইচ্ছাকৃত সমন্বয়, তবু পটাসিয়াম দেখুন।"),
    ("cetirizine", "fexofenadine", "moderate",
     "Duplicate antihistamine therapy",
     "একই শ্রেণির দুটি অ্যান্টিহিস্টামিন",
     "Prescribe only one antihistamine.",
     "শুধু একটি অ্যান্টিহিস্টামিন দিন।"),
    ("cetirizine", "diazepam", "moderate",
     "Additive sedation",
     "অতিরিক্ত ঘুম ঘুম ভাব",
     "Warn against driving or operating machinery.",
     "গাড়ি বা যন্ত্র চালানো থেকে বিরত থাকতে বলুন।"),
    ("paracetamol", "paracetamol", "major",
     "Duplicate paracetamol risks liver injury",
     "একই ওষুধ দুইবার, লিভারের ক্ষতির ঝুঁকি",
     "Check all brands; total daily dose must stay under 4 g.",
     "সব ব্র্যান্ড মিলিয়ে দৈনিক ৪ গ্রামের নিচে রাখুন।"),
]


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)

    brands = sorted(set(BRANDS))
    with open(OUT / "bd_brand_aliases.csv", "w", newline="", encoding="utf-8") as handle:
        writer = csv.writer(handle)
        writer.writerow(["brand", "generic"])
        writer.writerows(brands)

    with open(OUT / "drug_interactions.csv", "w", newline="", encoding="utf-8") as handle:
        writer = csv.writer(handle)
        writer.writerow(
            ["drug_a", "drug_b", "severity", "effect_en", "effect_bn",
             "advice_en", "advice_bn"]
        )
        writer.writerows(INTERACTIONS)

    generics = sorted({generic for _brand, generic in brands})
    print(f"brand aliases = {len(brands)} covering {len(generics)} generics")
    print(f"interaction pairs = {len(INTERACTIONS)} -> {OUT}")


if __name__ == "__main__":
    main()
