"""add ai_feedback table

Revision ID: b49ae5881a18
Revises: 20260709_0001
Create Date: 2026-07-22 21:56:44.657366
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = 'b49ae5881a18'
down_revision: Union[str, Sequence[str], None] = '20260709_0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_feedback',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('feature', sa.String(), nullable=False),
    sa.Column('input_text', sa.Text(), nullable=True),
    sa.Column('corrected_level', sa.Integer(), nullable=True),
    sa.Column('correct', sa.Boolean(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ai_feedback')
    # ### end Alembic commands ###